version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+mysqlconnector://root:projetinhos2025@db/quiosque_db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: projetinhos2025
      MYSQL_DATABASE: quiosque_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: